[project]
name = "extended-euclidean-algorithm"
version = "0.1.1"
description = "Returns the Bézout coefficients and gcd of two integers, useful for modular inverses and Diophantine equation solving."
requires-python = ">=3.10"
dependencies = []
readme = "README.md"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
